### ISSUE TITLE
PRACTICA 2 Visual Estudio UI

### ISSUE THREAD

**Issue by HECTOR-KDM02** [SistemasTecTlaxiaco/actividad-2de-practica-interfaz-grafica-con-c-team-ola#1]
(REPORTE)

[Practica 2 visual estudio.pdf](https://github.com/SistemasTecTlaxiaco/actividad-2de-practica-interfaz-grafica-con-c-team-ola/files/14324944/Practica.2.visual.estudio.pdf)

**Comment by josealfredo79** [comment]
Calificacion....

**Comment by Bryan080204** [comment]
Despues de revisar su reporte a detalle determinamos que su calificacion es 
19.4

cumple con la mayoria de las rubricas

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
